name: .NET Framework Desktop Build

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Cache packages to speed up builds
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            TinyOPDS\packages
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Restore packages for entire solution
      - name: Restore NuGet packages
        run: nuget restore TinyOPDS.sln

      # Build entire solution in Release mode
      - name: Build solution
        run: msbuild TinyOPDS.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      # Verify that files exist
      - name: List build output
        shell: powershell
        run: |
          Write-Host "TinyOPDS output:"
          Get-ChildItem -Path TinyOPDS\bin\Release\
          Write-Host ""
          Write-Host "TinyOPDSCLI output:"
          Get-ChildItem -Path TinyOPDSCLI\bin\Release\

      # Create artifacts for every build
      - name: Upload TinyOPDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDS-${{ github.sha }}
          path: TinyOPDS\bin\Release\TinyOPDS.exe
          retention-days: 30

      - name: Upload TinyOPDSCLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDSCLI-${{ github.sha }}
          path: TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe
          retention-days: 30

      # Upload to release only when a release is created
      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TinyOPDS\bin\Release\TinyOPDS.exe
            TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
