name: .NET Framework Desktop Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      # Cache packages to speed up builds
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            TinyOPDS\packages
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Restore packages for TinyOPDS
      - name: Restore NuGet packages for TinyOPDS
        run: nuget restore TinyOPDS\TinyOPDS.csproj -PackagesDirectory TinyOPDS\packages

      # Restore packages for TinyOPDSCLI (uses same packages folder)
      - name: Restore NuGet packages for TinyOPDSCLI  
        run: nuget restore TinyOPDSCLI\TinyOPDSCLI.csproj -PackagesDirectory TinyOPDS\packages

      # Build entire solution in Release mode
      - name: Build solution
        run: msbuild TinyOPDS.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      # Create artifacts for every build
      - name: Upload TinyOPDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDS-${{ github.sha }}
          path: TinyOPDS\bin\Release\TinyOPDS.exe
          retention-days: 30

      - name: Upload TinyOPDSCLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDSCLI-${{ github.sha }}
          path: TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe
          retention-days: 30

      # Upload to release only when a release is created
      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TinyOPDS\bin\Release\TinyOPDS.exe
            TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}