name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Install SQLite package directly
      - name: Install SQLite NuGet package
        run: |
          # Create packages directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path "packages"
          
          # Install the specific SQLite package version directly into packages folder
          nuget install System.Data.SQLite.Core.FTS5 -Version 1.0.114.1 -OutputDirectory packages
          
          # Verify the targets file exists
          $targetsFile = "packages\System.Data.SQLite.Core.FTS5.1.0.114.1\build\net45\System.Data.SQLite.Core.FTS5.targets"
          if (Test-Path $targetsFile) {
            Write-Host "✓ SQLite targets file found at: $targetsFile"
            Write-Host "File size: $((Get-Item $targetsFile).Length) bytes"
          } else {
            Write-Host "✗ SQLite targets file NOT found at expected location"
            Write-Host "Checking what files exist in the SQLite package:"
            Get-ChildItem -Path "packages\System.Data.SQLite.Core.FTS5.1.0.114.1" -Recurse | ForEach-Object {
              Write-Host $_.FullName
            }
            exit 1
          }

      # Restore any other NuGet packages if needed
      - name: Restore NuGet packages
        run: nuget restore TinyOPDS.sln -PackagesDirectory packages

      - name: Build solution
        run: msbuild TinyOPDS.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TinyOPDS/bin/Release/TinyOPDS.exe
            TinyOPDSCLI/bin/Release/TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
