name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Create packages.config files to ensure NuGet knows what to restore
      - name: Create packages.config files
        run: |
          # Create packages.config for TinyOPDS
          @'
          <?xml version="1.0" encoding="utf-8"?>
          <packages>
            <package id="System.Data.SQLite.Core.FTS5" version="1.0.114.1" targetFramework="net48" />
          </packages>
          '@ | Out-File -FilePath "TinyOPDS\packages.config" -Encoding UTF8
          
          # Create packages.config for TinyOPDSCLI
          @'
          <?xml version="1.0" encoding="utf-8"?>
          <packages>
            <package id="System.Data.SQLite.Core.FTS5" version="1.0.114.1" targetFramework="net48" />
          </packages>
          '@ | Out-File -FilePath "TinyOPDSCLI\packages.config" -Encoding UTF8

      # Restore NuGet packages to packages folder (old style)
      - name: Restore NuGet packages
        run: |
          nuget restore TinyOPDS.sln -PackagesDirectory packages

      - name: Build solution
        run: msbuild TinyOPDS.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TinyOPDS/bin/Release/TinyOPDS.exe
            TinyOPDSCLI/bin/Release/TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
