name: .NET Framework Desktop Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Clear NuGet caches
        shell: pwsh
        run: nuget locals all -clear

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            packages
            TinyOPDS\packages
          key: nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            nuget-

      - name: Prepare SgmlReader package structure
        shell: pwsh
        run: |
          # Create SgmlReader package in BOTH locations to ensure compatibility
          $locations = @(
            "packages\SgmlReader.1.8.11\lib\4.0",
            "TinyOPDS\packages\SgmlReader.1.8.11\lib\4.0"
          )
          
          $sourcePath = "TinyOPDS\Libs\SgmlReaderDll.dll"
          
          if (-not (Test-Path $sourcePath)) {
            Write-Error "ERROR: SgmlReaderDll.dll not found at: $sourcePath"
            Write-Host "Checking if file exists in repository..."
            Get-ChildItem -Path "TinyOPDS\Libs" -File | Select-Object Name, Length
            exit 1
          }
          
          foreach ($packagePath in $locations) {
            Write-Host "Creating directory: $packagePath"
            New-Item -ItemType Directory -Force -Path $packagePath | Out-Null
            
            $targetPath = "$packagePath\SgmlReaderDll.dll"
            Copy-Item $sourcePath -Destination $targetPath -Force
            
            if (Test-Path $targetPath) {
              $fileInfo = Get-Item $targetPath
              Write-Host "✓ Copied to $targetPath (Size: $($fileInfo.Length) bytes)"
            } else {
              Write-Error "Failed to copy to $targetPath"
            }
          }
          
          Write-Host "`nVerifying package structure:"
          if (Test-Path "packages\SgmlReader.1.8.11") {
            Get-ChildItem -Path "packages\SgmlReader.1.8.11" -Recurse | Select-Object FullName
          }
          if (Test-Path "TinyOPDS\packages\SgmlReader.1.8.11") {
            Get-ChildItem -Path "TinyOPDS\packages\SgmlReader.1.8.11" -Recurse | Select-Object FullName
          }

      - name: Install SQLite packages
        run: |
          nuget install System.Data.SQLite.Core.FTS5 -Version 1.0.114.1 -OutputDirectory TinyOPDS\packages -NonInteractive -Source https://api.nuget.org/v3/index.json
          nuget install System.Data.SQLite.Core -Version 1.0.114.1 -OutputDirectory TinyOPDS\packages -NonInteractive -Source https://api.nuget.org/v3/index.json

      - name: Restore TinyOPDS packages
        run: nuget restore TinyOPDS\TinyOPDS.csproj -PackagesDirectory TinyOPDS\packages -NonInteractive -Source https://api.nuget.org/v3/index.json

      - name: Restore TinyOPDSCLI packages  
        run: nuget restore TinyOPDSCLI\TinyOPDSCLI.csproj -PackagesDirectory TinyOPDS\packages -NonInteractive -Source https://api.nuget.org/v3/index.json

      - name: Build
        run: msbuild TinyOPDS.sln /p:Configuration=Release /m

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            TinyOPDS/bin/Release/TinyOPDS.exe
            TinyOPDSCLI/bin/Release/TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
