name: .NET Framework Desktop Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Cache packages at TinyOPDS\packages because .csproj imports expect this relative path
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: TinyOPDS\packages
          key: nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            nuget-

      # Restore packages exactly where the projects expect them: TinyOPDS\packages\...
      - name: Restore NuGet packages
        run: nuget restore TinyOPDS.sln -PackagesDirectory TinyOPDS\packages

      - name: Build (Release)
        run: msbuild TinyOPDS.sln /p:Configuration=Release /m

      # Optional sanity check to ensure binaries exist
      - name: Verify executables
        shell: pwsh
        run: |
          $paths = @(
            "TinyOPDS\bin\Release\TinyOPDS.exe",
            "TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe"
          )
          $missing = @()
          foreach ($p in $paths) {
            if (Test-Path $p) {
              Write-Host "OK: $p"
            } else {
              $missing += $p
            }
          }
          if ($missing.Count -gt 0) {
            Write-Error "Missing build outputs:`n$($missing -join "`n")"
            exit 1
          }

      # Upload both executables as release assets
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TinyOPDS\bin\Release\TinyOPDS.exe
            TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
