name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Remove SQLite NuGet references from project files
      # Since SQLite DLLs are embedded as resources, we don't need the NuGet packages
      - name: Remove SQLite NuGet references from project files
        run: |
          # Function to remove SQLite references from a project file
          function Remove-SqliteReferences {
              param([string]$ProjectFile)
              
              $content = Get-Content $ProjectFile -Raw
              
              # Remove the Import statement for SQLite targets
              $content = $content -replace '(?s)\s*<Import Project="[^"]*System\.Data\.SQLite[^"]*"[^>]*/>',''
              
              # Remove the EnsureNuGetPackageBuildImports target
              $content = $content -replace '(?s)\s*<Target Name="EnsureNuGetPackageBuildImports".*?</Target>',''
              
              # Remove NuGetPackageImportStamp
              $content = $content -replace '(?s)\s*<NuGetPackageImportStamp>\s*</NuGetPackageImportStamp>',''
              
              # Save the modified file
              Set-Content -Path $ProjectFile -Value $content -Encoding UTF8 -NoNewline
              
              Write-Host "Modified $ProjectFile - removed SQLite NuGet references"
          }
          
          # Process both project files
          Remove-SqliteReferences "TinyOPDS\TinyOPDS.csproj"
          Remove-SqliteReferences "TinyOPDSCLI\TinyOPDSCLI.csproj"

      # Restore NuGet packages (in case there are other packages)
      - name: Restore NuGet packages
        run: nuget restore TinyOPDS.sln

      # Build solution
      - name: Build solution
        run: msbuild TinyOPDS.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      # Upload release assets
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TinyOPDS/bin/Release/TinyOPDS.exe
            TinyOPDSCLI/bin/Release/TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
