name: .NET Framework Desktop Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Clear NuGet caches
        shell: pwsh
        run: nuget locals all -clear

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: packages
          key: nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            nuget-

      - name: Prepare SgmlReader package structure
        shell: pwsh
        run: |
          # TinyOPDS expects packages at ..\packages (relative to TinyOPDS folder)
          # This means packages should be at solution root level
          $packagePath = "packages\SgmlReader.1.8.11\lib\4.0"
          
          Write-Host "Creating SgmlReader package directory: $packagePath"
          New-Item -ItemType Directory -Force -Path $packagePath
          
          # Copy SgmlReaderDll.dll from embedded Libs
          $sourcePath = "TinyOPDS\Libs\SgmlReaderDll.dll"
          $targetPath = "$packagePath\SgmlReaderDll.dll"
          
          if (Test-Path $sourcePath) {
            Copy-Item $sourcePath -Destination $targetPath -Force
            Write-Host "Copied SgmlReaderDll.dll to: $targetPath"
            
            # Verify the file was copied
            if (Test-Path $targetPath) {
              $fileInfo = Get-Item $targetPath
              Write-Host "File copied successfully. Size: $($fileInfo.Length) bytes"
            }
          } else {
            Write-Error "SgmlReaderDll.dll not found at: $sourcePath"
            exit 1
          }
          
          # List the package structure
          Write-Host "`nPackage structure:"
          Get-ChildItem -Path "packages" -Recurse | Select-Object FullName

      - name: Install SQLite packages
        run: |
          nuget install System.Data.SQLite.Core.FTS5 -Version 1.0.114.1 -OutputDirectory packages -NonInteractive -Source https://api.nuget.org/v3/index.json
          nuget install System.Data.SQLite.Core -Version 1.0.114.1 -OutputDirectory packages -NonInteractive -Source https://api.nuget.org/v3/index.json

      - name: Restore TinyOPDS packages
        run: nuget restore TinyOPDS\TinyOPDS.csproj -PackagesDirectory packages -NonInteractive -Source https://api.nuget.org/v3/index.json

      - name: Restore TinyOPDSCLI packages  
        run: nuget restore TinyOPDSCLI\TinyOPDSCLI.csproj -PackagesDirectory packages -NonInteractive -Source https://api.nuget.org/v3/index.json

      - name: Build
        run: msbuild TinyOPDS.sln /p:Configuration=Release /m

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            TinyOPDS/bin/Release/TinyOPDS.exe
            TinyOPDSCLI/bin/Release/TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
