name: .NET Framework Desktop Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: NuGet diagnostics (clear caches)
        shell: pwsh
        run: |
          nuget locals all -clear
          nuget sources list

      - name: Cache NuGet packages (packages.config layout)
        uses: actions/cache@v4
        with:
          path: TinyOPDS\packages
          key: nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            nuget-

      # Restore packages exactly where .csproj expects: TinyOPDS\packages relative to the solution root
      - name: Restore TinyOPDS packages
        run: nuget restore TinyOPDS\TinyOPDS.csproj -NonInteractive -PackagesDirectory TinyOPDS\packages -Source https://api.nuget.org/v3/index.json

      - name: Restore TinyOPDSCLI packages
        run: nuget restore TinyOPDSCLI\TinyOPDSCLI.csproj -NonInteractive -PackagesDirectory TinyOPDS\packages -Source https://api.nuget.org/v3/index.json

      - name: Build (Release)
        run: msbuild TinyOPDS.sln /p:Configuration=Release /m

      - name: Verify executables
        shell: pwsh
        run: |
          $paths = @(
            'TinyOPDS\bin\Release\TinyOPDS.exe',
            'TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe'
          )
          $missing = @()
          foreach ($p in $paths) {
            if (Test-Path $p) { Write-Host "OK: $p" } else { $missing += $p }
          }
          if ($missing.Count -gt 0) {
            Write-Error ("Missing build outputs:`n" + ($missing -join "`n"))
            exit 1
          }

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TinyOPDS\bin\Release\TinyOPDS.exe
            TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
