name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build TinyOPDS (.NET Framework 4.8)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # For projects using packages.config restore must be done via nuget.exe
      - name: Restore NuGet packages
        run: nuget restore TinyOPDS.sln -Verbosity detailed

      - name: Build (Release)
        run: msbuild TinyOPDS.sln /p:Configuration=Release /m /v:m

      # Optional: show where the Sign folder is if PostBuildEvent created it
      - name: List outputs
        shell: pwsh
        run: |
          Write-Host "Solution dir:" (Get-Location).Path
          Get-ChildItem -Recurse -Force TinyOPDS\bin\Release | Select-Object FullName,Length
          Get-ChildItem -Recurse -Force TinyOPDSCLI\bin\Release | Select-Object FullName,Length
          if (Test-Path ".\Sign") { Get-ChildItem -Recurse -Force .\Sign | Select-Object FullName,Length }

      - name: Upload TinyOPDS artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDS_Release
          path: |
            TinyOPDS\bin\Release\**
          if-no-files-found: warn
          compression-level: 9

      - name: Upload TinyOPDSCLI artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDSCLI_Release
          path: |
            TinyOPDSCLI\bin\Release\**
          if-no-files-found: warn
          compression-level: 9

      - name: Upload Sign folder (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Sign_Folder
          path: |
            Sign\**
            **\Sign\**
          if-no-files-found: ignore
          compression-level: 9
