name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build TinyOPDS (.NET Framework 4.8)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # >>> КЛЮЧЕВОЕ: положить SgmlReader именно в ./packages, как ожидают .csproj
      - name: Preinstall SgmlReader package for packages.config layout
        run: nuget install SgmlReader -Version 1.8.11 -OutputDirectory packages

      # Остальные пакеты (EpubSharp, SQLite и т.п.) через стандартный restore
      - name: Restore NuGet packages
        run: nuget restore TinyOPDS.sln -Verbosity detailed

      - name: Verify SgmlReader presence
        shell: pwsh
        run: |
          $p = Join-Path $PWD "packages\SgmlReader.1.8.11\lib\4.0\SgmlReaderDll.dll"
          if (-not (Test-Path $p)) {
            Write-Error "SgmlReaderDll not found at $p"
            exit 1
          }
          Write-Host "OK: $p"

      - name: Build (Release)
        run: msbuild TinyOPDS.sln /p:Configuration=Release /m /v:m

      - name: List outputs
        if: always()
        shell: pwsh
        run: |
          Write-Host "== TinyOPDS bin/Release =="
          if (Test-Path ".\TinyOPDS\bin\Release") { Get-ChildItem -Recurse -Force .\TinyOPDS\bin\Release | Select-Object FullName,Length }
          Write-Host "== TinyOPDSCLI bin/Release =="
          if (Test-Path ".\TinyOPDSCLI\bin\Release") { Get-ChildItem -Recurse -Force .\TinyOPDSCLI\bin\Release | Select-Object FullName,Length }
          if (Test-Path ".\Sign") { Write-Host "== Sign =="; Get-ChildItem -Recurse -Force .\Sign | Select-Object FullName,Length }

      - name: Upload TinyOPDS artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDS_Release
          path: TinyOPDS\bin\Release\**
          if-no-files-found: warn
          compression-level: 9

      - name: Upload TinyOPDSCLI artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TinyOPDSCLI_Release
          path: TinyOPDSCLI\bin\Release\**
          if-no-files-found: warn
          compression-level: 9

      - name: Upload Sign folder (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Sign_Folder
          path: |
            Sign\**
            **\Sign\**
          if-no-files-found: ignore
          compression-level: 9
