name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Restore packages for entire solution
      - name: Restore NuGet packages
        run: nuget restore TinyOPDS.sln

      # Build entire solution in Release mode
      - name: Build solution
        run: msbuild TinyOPDS.sln /p:Configuration=Release /p:Platform="Any CPU" /m

      # Verify that files exist
      - name: Verify build output
        shell: powershell
        run: |
          $tinyOPDS = "TinyOPDS\bin\Release\TinyOPDS.exe"
          $tinyOPDSCLI = "TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe"
          
          if (!(Test-Path $tinyOPDS)) {
            Write-Error "TinyOPDS.exe not found at $tinyOPDS"
            exit 1
          }
          if (!(Test-Path $tinyOPDSCLI)) {
            Write-Error "TinyOPDSCLI.exe not found at $tinyOPDSCLI"
            exit 1
          }
          
          Write-Host "✓ TinyOPDS.exe found"
          Write-Host "✓ TinyOPDSCLI.exe found"

      # Upload both executables to the release
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TinyOPDS\bin\Release\TinyOPDS.exe
            TinyOPDSCLI\bin\Release\TinyOPDSCLI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
